name       : fftw
version    : 3.3.4
release    : 1
source     :
    - http://www.fftw.org/fftw-3.3.4.tar.gz : 8f0cde90929bc05587c3368d2f15cd0530a60b8a9912a8e2979a72dbe5af0982
license    : GPL-2.0
summary    : FFTW Fourier transform library
description: |
    FFTW is a C subroutine library for computing the discrete Fourier transform (DFT) in one or more dimensions, of arbitrary input size, and of both real and complex data (as well as of even/odd data, i.e. the discrete cosine/sine transforms or DCT/DST).
builddeps  :
setup      : |
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
