name       : fftw
version    : 3.3.6
release    : 7
source     :
    - http://fftw.org/fftw-3.3.6-pl1.tar.gz : 1ef4aa8427d9785839bc767f3eb6a84fcb5e9a37c31ed77a04e7e047519a183d
license    : GPL-2.0
summary    : FFTW Fourier transform library
description: |
    FFTW is a C subroutine library for computing the discrete Fourier transform (DFT) in one or more dimensions, of arbitrary input size, and of both real and complex data (as well as of even/odd data, i.e. the discrete cosine/sine transforms or DCT/DST).
component  : programming
builddeps  :
    - gfortran
    - libpth-devel
setup      : |
    CONFOPTS="$CONFOPTS --prefix=/usr --libdir=%libdir% --disable-static --enable-shared --enable-openmp --enable-sse2 --enable-threads"
    mkdir .fftw-single
    mv * .fftw-single/ && mv .fftw-single fftw-single
    cp -R fftw-single fftw-double
    # Single precision
    cd fftw-single/
    ./configure $CONFOPTS --enable-float
    # Double precision
    cd ../fftw-double/
    ./configure $CONFOPTS --enable-avx
build      : |
    cd $workdir/fftw-single/
    %make
    %make_install
    cd $workdir/fftw-double/
    %make
    %make_install
